V3
saucal/action-deploy-ssh pull request #3
Opened 2023-11-17 12:01 UTC by ksere

PR opened for the purpose of reviewing. **NOT TO BE MERGED**

Rel. [task](https://app.clickup.com/t/862kjndjn)

2023-11-17 17:38 UTC, dpanta94 approved these changes
LGTM!

2023-11-28 18:23 UTC, msaggiorato requested changes

2023-11-28 18:23 UTC, msaggiorato commented on main.js
> +				CONSISTENCY_CHECK: ( manifest != '' ? 'true' : 'false' ),
shouldn't we also check for the `consistencyCheck` variable here?

2023-11-28 18:23 UTC, msaggiorato commented on main.js
> +				REMOTE_ROOT: remoteRoot,
Remote root is not necessarily the wp path. it's most of the time the wp-content path, but nothing guarantees it. Not sure how well WP CLI handles this.

2023-12-08 14:38 UTC, ksere commented on main.js
> +				REMOTE_ROOT: remoteRoot,
If you are in any folder deeper that wp root, it works properly.

2024-01-12 17:56 UTC, closed without merging